// app/javascript/components/bathroom.svelte
<script context="module">
  import gql from 'graphql-tag';

  const getBathroom = gql`
    fragment getBathroom on Location {
      bathroomCode
    }
  `;

  export const fragments = {
    getBathroom,
  };
</script>
<script>
  export let bathroomCode;
</script>

<style>
  .wifi {
    display: flex;
    flex-direction: column;
    margin-top: 100px;
  }
</style>

<div class="wifi">
  <div>BATHROOM CODE</div>
  <div>{bathroomCode}</div>
</div>

// app/javascript/components/bathroom.jsx
import React from 'react';
import PropTypes from 'prop-types';
import gql from 'graphql-tag';
import styled from 'styled-components';
import { WhiteSubTitle, WhiteTitleLarge } from '@components/typography';
import { LoadingMessage, ErrorMessage } from '@messages/default-messages';
import withFragment from './hocs/with-fragment';

export const getBathroomCode = gql`
  fragment Bathroom on Location {
    bathroomCode
  }
`;

const Column = styled.div`
  display: flex;
  flex-direction: column;
  margin-top: 100px;
`;

export const Bathroom = ({ loading, error, location }) => {
  if (loading) {
    return <LoadingMessage />;
  }
  if (error) {
    return <ErrorMessage />;
  }

  const { bathroomCode } = location;
  if (!bathroomCode) {
    return null;
  }
  return (
    <Column>
      <WhiteSubTitle>BATHROOM CODE</WhiteSubTitle>
      <WhiteTitleLarge>{bathroomCode}</WhiteTitleLarge>
    </Column>
  );
};

Bathroom.propTypes = {
  location: PropTypes.shape({
    bathroomCode: PropTypes.string,
  }),
  loading: PropTypes.bool,
  error: PropTypes.bool,
};

Bathroom.defaultProps = {
  location: {},
  loading: true,
  error: false,
};

Bathroom.fragments = {
  location: getBathroomCode,
};

export default withFragment(Bathroom);
